name: Build Executables (Go)

on:
  push:
    branches:
      - main
      - develop
      - feat/*
    tags:
      - 'v*'
  pull_request:
    branches:
      - main
      - develop
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            goos: linux
            goarch: amd64
            ext: ""
            shell: bash
          - os: windows-latest
            goos: windows
            goarch: amd64
            ext: .exe
            shell: powershell
          - os: macos-latest
            goos: darwin
            goarch: amd64
            ext: ""
            shell: bash
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Build
        shell: bash
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
        run: |
          mkdir -p bin
          go build -ldflags="-s -w" -o bin/blip-list-generator-${{ matrix.goos }}${{ matrix.ext }} ./cmd/blip-list-generator

      - name: Show build info (Unix)
        if: matrix.os != 'windows-latest'
        run: |
          ls -lh bin/
          file bin/blip-list-generator-${{ matrix.goos }}${{ matrix.ext }} || true

      - name: Show build info (Windows)
        if: matrix.os == 'windows-latest'
        shell: powershell
        run: |
          Get-ChildItem -Path bin\

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: blip-list-generator-${{ matrix.goos }}${{ matrix.ext }}
          path: bin/blip-list-generator-${{ matrix.goos }}${{ matrix.ext }}

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    permissions:
      contents: write
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            blip-list-generator-linux/blip-list-generator-linux
            blip-list-generator-windows.exe/blip-list-generator-windows.exe
            blip-list-generator-darwin/blip-list-generator-darwin
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
